name: "Deploy docker images to nomad"

inputs:
  nomad-addr:
    description: "Nomad domain address"
    required: true
  nomad-ca-cert:
    description: "Nomad CA cert"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup `nomad`
      uses: lucasmelin/setup-nomad@v2
      id: setup
      with:
        version: ${{ env.NOMAD_VERSION }}
      env:
        NOMAD_VERSION: "1.8.1"

    - name: Auth Into Nomad
      id: nomad-jwt-auth
      uses: mikenomitch/nomad-jwt-auth@v0.1.0
      with:
        url: ${{ inputs.nomad-addr }}
        caCertificate: ${{ inputs.nomad-ca-cert }}

    - name: Check nomad status
      shell: bash
      run: NOMAD_ADDR="${{ inputs.nomad-addr }}" NOMAD_TOKEN="${{ steps.nomad-jwt-auth.outputs.nomadToken }}" nomad status

    - name: Deploy nomad job
      shell: bash
      run: NOMAD_ADDR="${{ inputs.nomad-addr }}" NOMAD_TOKEN="${{ steps.nomad-jwt-auth.outputs.nomadToken }}" nomad job run .nomad/job.hcl